shape_edge_detector:
  bound_presets:
    static_img:
      bound1:
        lower: [55, 0, 159]      #S
        upper: [180, 255, 255]
      bound2:
        lower: [0, 132, 151]
        upper: [42, 255, 255]
    
    dynamic_regular:
      blue_and_purple:
        lower: [55, 0, 159]
        upper: [180, 255, 255]
      red_and_yellow:
        lower: [0, 134, 176]
        upper: [54, 255, 255]
      dark_green:
        lower: [51, 164, 163]
        upper: [57, 255, 171]

    black:
      bound1:
        lower: [0, 13, 71]
        upper: [180, 255, 255]

  preset: black
