
# video_path: "/home/yliu08/workspaces/pennair-application/resource/PennAir 2024 App Dynamic.mp4" #dynamic_regular
video_path: "/home/yliu08/workspaces/pennair-application/resource/PennAir 2024 App Dynamic Hard.mp4" #dynamic_hard